branch-defaults:
  proxy:
    environment: yalp-reviews-service-dev
environment-defaults:
  yalp-reviews-service-dev:
    branch: null
    repository: null
global:
  application_name: yalp-reviews-service
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-1::platform/Node.js running on
    64bit Amazon Linux/4.5.1
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
